import Tagify from '@yaireo/tagify'
let input = document.querySelector('input[name=name]'),
	tagify = new Tagify(input, {
		whitelist : ['AngularJS',
		'Application Development',
		'Mobile Applications',
		'Data Imports',
		'Install, Maintain, & Merge Databases',
		'Optimize Database',
		'Database',
		'Database Administration',
		'Information Architecture',
		'IT Optimization',
		'Storage',
		'Configure Database Software',
		'Architecture',
		'Data Storage',
		'Servers',
		'Big Data',
		'Deployment Automation Tools',
		'IT Security',
		'APIs',
		'Design Specifications',
		'Software Developer',
		'Interaction Flows',
		'IT Solutions',
		'Software Development',
		'Systems Software',
		'Security',
		'Information Systems',
		'Open Source Technology Integration',
		'Process Flows',
		'Software Engineering'],
		dropdown : {
			classname : "color-blue",
			enabled   : 3,
			maxItems  : 5
		}
});